# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables (optional)
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Expose PostgreSQL port
EXPOSE 5432
